### ISSUE TITLE
Cannot open the Mousedroid.exe file because of missing dll files

### ISSUE THREAD

**Issue by appledino3604** [hypertensiune/Mousedroid#12]
I wanted to try out mousedroid, bit when i opened the exe file it showed the following errors. It seems the exe requires 32 bit dll files
which are not present in my PC since i run x64 based Windows and cannot find them online either. Please include the following files in 
the zip file or kindly help me fix it.

libstdc++-6.dll
libgcc_s_seh-1.dll

both of them are 32 bit

**Comment by hypertensiune** [comment]
These should fix your problem

[dlls.zip](https://github.com/user-attachments/files/17356110/dlls.zip)

**Comment by appledino3604** [comment]
Thank you the issue is fixed now.
